# crud user
GET http://localhost:3000/api/user

###
GET http://localhost:3000/api/user/644098d6f15e8f6834217787

###
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "name": "Vinka",
  "email": "vinkaafiyata@gmail.com",
  "password": "123",
  "role": "user",
  "phonenumber": "089878712979"
}

###
DELETE  http://localhost:3000/api/user/delete/6440951f5132567922445a18

###
PUT  http://localhost:3000/api/user/update/644098d6f15e8f6834217787
Content-Type: application/json

{
  "name": "test2",
  "email": "test2@gmail.com",
  "password": "1234",
  "role": "user",
  "phonenumber": "088227852900aja"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "afiyata@gmail.com",
  "password": "12345"
}

### productcategory 
GET http://localhost:3000/api/productcategory

###
POST http://localhost:3000/api/productcategory/add
Content-Type: application/json

{
  "name": "Pedas"
}

###
PUT  http://localhost:3000/api/productcategory/update/6446a8687bfbd0230f4c1ea4
Content-Type: application/json

{
  "name": "Pedas pisan"
}

###
DELETE http://localhost:3000/api/productcategory/delete/6448bf82f53690f026c3115e

### product
GET http://localhost:3000/api/products

###
GET http://localhost:3000/api/products/boci-cuanki

###
POST http://localhost:3000/api/products/add
Content-Type: application/json

{
  "name": "Cimoring Pedas",
  "price": 11000,
  "stock": 10,
  "path": "cimoring-pedas",
  "notes": "",
  "description": "Cimoring pedasnya muantap!",
  "images": ["https://drive.google.com/uc?export=view&id=1z-0WojPC-lgxfF5AEjiI_yTRTz0PVFtS","https://drive.google.com/uc?export=view&id=1omCnzOjh2Okvo9LznHbDSjU7seDTFsWW"],
  "categories": ["644d391cfb2bef2a6cf7697f"]
}

###
PUT http://localhost:3000/api/products/update/644d3d93fb2bef2a6cf76983
Content-Type: application/json

{
  "name": "Boci Cuanki",
  "price": 11000,
  "stock": 10,
  "path": "boci-cuanki",
  "notes": "*Produk dibuat berdasarkan pesanan. Masa ketahanan produk setelah diterima: 30 hari.",
  "description": "Boci cuanki alias baso aci yang kriuknya dan kuahnya bikin mau lagi. Enak dikonsumsi tanpa bumbu atau dengan bumbu pilihan dan level kepedasan.",
  "images": ["https://drive.google.com/uc?export=view&id=1z-0WojPC-lgxfF5AEjiI_yTRTz0PVFtS","https://drive.google.com/uc?export=view&id=1omCnzOjh2Okvo9LznHbDSjU7seDTFsWW"],
  "categories": ["644d391cfb2bef2a6cf7697f"]
}

###
POST http://localhost:3001/api/cart/add
Content-Type: application/json

{
  "items": [
    {
      "product": "644d3d93fb2bef2a6cf76983",
      "qty": 2
    }
  ],
  "totalQty": 2,
  "totalRp": 22000,
  "user": "645f9c7609978b052253b8ec"
}