export {default as LoginPage} from './login'
export {default as Text} from './atoms/Text'
export {default as PageAdmin} from './templates/admin/PageAdmin'
export {default as Input} from './register/Input'
export {default as InputPassword} from './register/InputPassword'
export {default as Alert} from './register/Alert'
export {default as Loader} from './global/Loader'